name: Tests

on:
  push:
  pull_request:

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.11]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |

          apt -q update
          ~/.pyenv/bin/pyenv install -s 3.11.0
          ~/.pyenv/bin/pyenv virtualenv 3.11.0 venv
          ~/.pyenv/bin/pyenv local venv

          pip install tox tox-gh-actions
          pip install -r requirements.txt pytest

      - name: Run tests with tox
        run: tox
