name: Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  tests:
#    runs-on: ${{ matrix.os }}
    runs-on: self-hosted
    if: >
      github.event_name == 'pull_request' || 
      (github.event_name == 'push' && 
      contains(github.event.head_commit.message, 'CACHE UPDATE'))

    strategy:
      matrix:
#        os: [macos-latest]
        os: [windows-latest]
        python-version: [3.9.13]

    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true # Ensure Git LFS objects are checked out

      - name: Cache LFS objects
        id: cache-lfs
        uses: actions/cache@v3
        with:
          path: |
            .git/lfs/objects
          key: ${{ runner.os }}-lfs-354e74cf3a5d8965860a44fa6163c1ad59a81cdc
          restore-keys: |
            ${{ runner.os }}-lfs-354e74cf3a5d8965860a44fa6163c1ad59a81cdc

      - name: Fetch LFS objects if needed
        if: steps.cache-lfs.outputs.cache-hit != 'true'
        run: git lfs pull

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Cache requirements
        id: cache-requirements
        uses: actions/cache@v2
        with:
          path: |
            .tox

          key: ${{ runner.os }}-tox-${{ matrix.python-version }}-${{ hashFiles('requirements.txt', 'tox.ini') }}
          restore-keys: |
            ${{ runner.os }}-tox-${{ matrix.python-version }}-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pytest
          python -m pip install pytest-cov
          pip install tox tox-gh-actions

      - name: Run tests with tox
        run: tox
